school/urls.py
from django.contrib import admin
from django.urls import path, include
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions


schema_view = get_schema_view(
    openapi.Info(
        title="School API",
        default_version='v1',
        description="SCHOOL",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="argen.kubatbekov@gmail.com"),
        license=openapi.License(name="BSD License"),
        dochost="http://127.0.0.1:8000",
        schemes=['http', 'https'],
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('students/', include('students.urls')),
]

students/urls.py
from django.urls import path
from .views import StudentListView, StudentCreateView, StudentDetailView, StudentUpdateView, StudentDeleteView, home

app_name = 'students'

urlpatterns = [
    path('', StudentListView.as_view(), name='student_list'),
    path('create/', StudentCreateView.as_view(), name='student_create'),
    path('<int:pk>/', StudentDetailView.as_view(), name='student_detail'),
    path('<int:pk>/update/', StudentUpdateView.as_view(), name='student_update'),
    path('<int:pk>/delete/', StudentDeleteView.as_view(), name='student_delete'),
    path('home/', home, name='home'),
]

users/urls.py
from django.urls import path
from .views import TeacherRegistrationView, SearchStudentsView, TeacherLoginView


urlpatterns = [
    path('register/teacher/', TeacherRegistrationView.as_view(), name='register_teacher'),
    path('search/', SearchStudentsView.as_view(), name='search_students'),
    path('login/', TeacherLoginView.as_view(), name='teacher_login'),
]

students/models.py
from django.db import models

# Create your models here.

users/models.py
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.hashers import check_password
from django.contrib.auth.models import AbstractUser
from django.core.mail import send_mail
from django.db import models
from django.db.models.signals import pre_save, post_save
from django.dispatch import receiver

from school import settings


class Student(models.Model):
    name = models.CharField(verbose_name='Имя', max_length=50)
    surname = models.CharField(verbose_name='Фамилия', max_length=50)
    father_name = models.CharField(verbose_name='Отчество', max_length=50, blank=True, null=True)
    email = models.EmailField(verbose_name='Email', unique=True, null=True, blank=True)
    birthday = models.DateField(verbose_name='Дата рождения')
    address = models.CharField(verbose_name='Адрес', max_length=200)
    gender = models.CharField(max_length=1, choices=[('M', 'Male'), ('Ж', 'Female')])
    photo = models.ImageField(verbose_name='Фото', upload_to='photos/%Y/%m/%d/', blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Студент'
        verbose_name_plural = 'Студенты'

@receiver(post_save, sender=Student)
def send_email(sender, instance, created, **kwargs):
    if created:
        subject = 'Добро пожаловать!'
        message = f'Дорогой {instance.name},\n\nДобро пожаловать в нашу школу!'
        from_email = settings.EMAIL_HOST_USER
        to_email = [instance.email]
        send_mail(subject, message, from_email, to_email)


class Teacher(AbstractUser):
    phone = models.CharField(verbose_name='Номер телефона', max_length=20, unique=True)
    class_number = models.CharField(verbose_name='Класс', max_length=10)
    subject = models.CharField(verbose_name='Предмет', max_length=50)


    def __str__(self):
        return self.username

    class Meta:
        verbose_name = 'Учитель'
        verbose_name_plural = 'Учителя'


class ClassRoom(models.Model):
    name = models.CharField(max_length=100)
    teacher = models.OneToOneField('Teacher', on_delete=models.CASCADE, related_name='classroom')
    students = models.ManyToManyField('Student', related_name='classes')

    class Meta:
        verbose_name = 'Класс'
        verbose_name_plural = 'Классы'

class School(models.Model):
    name = models.CharField(max_length=100)
    classes = models.ManyToManyField('ClassRoom', related_name='schools')

    class Meta:
        verbose_name = 'Школа'
        verbose_name_plural = 'Школы'

students/forms.py
from django import forms
from users.models import Student

class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['name', 'surname', 'email', 'birthday', 'address', 'gender', 'photo']

students/views.py
from django.conf import settings
from django.core.mail import send_mail
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.template.loader import render_to_string
from django.views import View
from users.models import Student
from .forms import StudentForm

class StudentListView(View):
    def get(self, request):
        students = Student.objects.all()
        return render(request, 'students/student_list.html', {'students': students})

class StudentDetailView(View):
    def get(self, request, pk):
        student = get_object_or_404(Student, pk=pk)
        return render(request, 'students/student_detail.html', {'student': student})

class StudentCreateView(View):
    def get(self, request):
        form = StudentForm()
        return render(request, 'students/student_form.html', {'form': form})

    def post(self, request):
        form = StudentForm(request.POST)
        if form.is_valid():
            new_student = form.save()
            #
            # subject = 'Добро пожаловать!'
            # message = f'Дорогой {new_student.name},\n\nДобро пожаловать в нашу школу!'
            # from_email = settings.EMAIL_HOST_USER
            # to_email = [new_student.email]
            # send_mail(subject, message, from_email, to_email)

            return HttpResponse("Студент успешно создан.<br>"
                                "<a href='/students/home/'>Вернуться на главную страницу</a><br>")
        return render(request, 'students/student_form.html', {'form': form})

class StudentUpdateView(View):
    def get(self, request, pk):
        student = get_object_or_404(Student, pk=pk)
        form = StudentForm(instance=student)
        return render(request, 'students/student_form.html', {'form': form})

    def post(self, request, pk):
        student = get_object_or_404(Student, pk=pk)
        form = StudentForm(request.POST, instance=student)
        if form.is_valid():
            form.save()
            return redirect('student_list')
        return render(request, 'students/student_form.html', {'form': form})

class StudentDeleteView(View):
    def get(self, request, pk):
        student = get_object_or_404(Student, pk=pk)
        return render(request, 'students/student_confirm_delete.html', {'student': student})

    def post(self, request, pk):
        student = get_object_or_404(Student, pk=pk)
        student.delete()
        return HttpResponse("Студент успешно удален. "
                            "<a href='/students/home/'>Вернуться на главную страницу</a>")


def home(request):
    return render(request, 'students/home.html')

students/templates/students/home.html
<!DOCTYPE html>
<html>
<head>
    <title>Главная страница</title>
</head>
<body>
    <h1>Главное меню</h1>
    <ul>
        <li><a href="{% url 'register_teacher' %}">Регистрация учителя</a></li>
        <li><a href="{% url 'students:student_list' %}">Список студентов</a></li>
        <li><a href="{% url 'teacher_login' %}">Вход для учителя</a></li>
        <li><a href="{% url 'students:student_create' %}">Добавить студента</a></li>
    </ul>
</body>
</html>

students/templates/students/student_confirm_delete.html
<!DOCTYPE html>
<html>
<head>
    <title>Подтверждение удаления студента</title>
</head>
<body>
    <h1>Вы уверены, что хотите удалить студента "{{ student.name }} {{ student.surname }}"?</h1>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Удалить</button>
    </form>
</body>
</html>

students/templates/students/student_deleted.html
<!DOCTYPE html>
<html>
<head>
    <title>Студент удален</title>
</head>
<body>
    <h1>Студент успешно удален</h1>
    <a href="{% url 'students:home' %}">На главную страницу</a>
</body>
</html>

students/templates/students/student_detail.html
<!DOCTYPE html>
<html>
<head>
    <title>Информация о студенте</title>
</head>
<body>
    <h1>Информация о студенте</h1>
    <p>Имя: {{ student.name }}</p>
    <p>Фамилия: {{ student.surname }}</p>
    <p>Email: {{ student.email }}</p>
    <p>Дата рождения: {{ student.birthday }}</p>
    <p>Адрес: {{ student.adress }}</p>
    <p>Пол: {{ student.get_gender_display }}</p>
    <a href="{% url 'students:home' %}">Вернуться в главное меню</a>
</body>
</html>

students/templates/students/student_form.html
<!DOCTYPE html>
<html>
<head>
    <title>Форма студента</title>
</head>
<body>
    <h1>Форма студента</h1>
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить</button>
    </form>
    <a href="{% url 'students:home' %}">Вернуться в главное меню</a>
</body>
</html>

students/templates/students/student_list.html
<!DOCTYPE html>
<html>
<head>
    <title>Список студентов</title>
</head>
<body>
    <h1>Список студентов</h1>
    <ul>
        {% for student in students %}
            <li><a href="{% url 'students:student_detail' pk=student.pk %}">{{ student.name }} {{ student.surname }}</a></li>
        {% endfor %}
    </ul>
    <a href="{% url 'students:home' %}">Вернуться в главное меню</a>
</body>
</html>